version: "3.8"

networks:
  proxy-net:
    external: true
  cocina-internal-net:
    driver: bridge

volumes:
  cocina_db_data:


services:
  cocina-db:
    image: postgres:15-alpine
    container_name: cocina-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-cocina}
      POSTGRES_USER: ${DB_USER:-cocina_user}
      POSTGRES_PASSWORD: ${DB_PASS:-cocina_pass}
    volumes:
      - cocina_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cocina-internal-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-cocina_user}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cocina-web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: cocina-web
    restart: unless-stopped
    environment:
      AUTH_TRUST_HOST: "true"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      AUTH_URL: "${AUTH_URL:-http://localhost:3010}"
      DATABASE_URL: postgresql://${DB_USER:-cocina_user}:${DB_PASS:-cocina_pass}@cocina-db:5432/${DB_NAME:-cocina}
      AUTH_SECRET: "${AUTH_SECRET:-supersecretkey123}" # Mandatory for NextAuth v5
    networks:
      - proxy-net
      - cocina-internal-net
    depends_on:
      cocina-db:
        condition: service_healthy
    ports:
      - "3010:3000"
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cocina-web.rule=Host(`cocina.sotodelprior.com`)"
      - "traefik.http.routers.cocina-web.entrypoints=websecure"
      - "traefik.http.routers.cocina-web.tls=true"
      - "traefik.http.routers.cocina-web.tls.certresolver=le"
      - "traefik.http.routers.cocina-web.service=cocina-web-svc"
      - "traefik.http.services.cocina-web-svc.loadbalancer.server.port=3000"

      # Redirect HTTP -> HTTPS
      - "traefik.http.routers.cocina-web-http.rule=Host(`cocina.sotodelprior.com`)"
      - "traefik.http.routers.cocina-web-http.entrypoints=web"
      - "traefik.http.routers.cocina-web-http.middlewares=cocina-https-redirect"
      - "traefik.http.middlewares.cocina-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.cocina-https-redirect.redirectscheme.permanent=true"

    extra_hosts:
      - "cocina.sotodelprior.com:host-gateway"
